<?php

namespace ORM\Attributes;

use Attribute;

/**
 * Specifies that the value of the property is auto-generated by the database.
 *
 * This is commonly used for primary keys (e.g., auto-increment columns).
 * Must be used together with #[Id] and #[Column].
 *
 * @example
 * ```php
 * #[Id]
 * #[GeneratedValue]
 * #[Column(type: "int")]
 * private int $id;
 * ```
 *
 * @see Id
 * @see Column
 * @see \ORM\MetadataParser
 */
#[Attribute(Attribute::TARGET_PROPERTY)]
class GeneratedValue {}
