services:
  php:
    build:
      context: ../ # Important: Set context to root
      dockerfile: docker/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    image: orm:latest
    container_name: orm_cli
    develop:
      watch:
        - action: sync+restart
          path: ../src/
          target: /app/src/
    depends_on:
      mariadb:
        condition: service_healthy
    stdin_open: true
    tty: true

  mariadb:
    image: mariadb:latest
    container_name: orm_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=orm
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - orm_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d/:ro

volumes:
  orm_data: